/*
 * Vectorizer.AI API
 * OpenAPI 3.0 specification for the Vectorizer.AI image vectorization API. Authenticate with HTTP Basic auth, using your API Id as the username and your API Secret as the password.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vectorizer.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.vectorizer.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * AccountStatusResponse
 */
@JsonPropertyOrder({
  AccountStatusResponse.JSON_PROPERTY_SUBSCRIPTION_PLAN,
  AccountStatusResponse.JSON_PROPERTY_SUBSCRIPTION_STATE,
  AccountStatusResponse.JSON_PROPERTY_CREDITS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.6.0")
public class AccountStatusResponse {
  public static final String JSON_PROPERTY_SUBSCRIPTION_PLAN = "subscriptionPlan";
  private String subscriptionPlan;

  public static final String JSON_PROPERTY_SUBSCRIPTION_STATE = "subscriptionState";
  private String subscriptionState;

  public static final String JSON_PROPERTY_CREDITS = "credits";
  private Double credits;

  public AccountStatusResponse() { 
  }

  public AccountStatusResponse subscriptionPlan(String subscriptionPlan) {
    this.subscriptionPlan = subscriptionPlan;
    return this;
  }

   /**
   * The subscription plan currently associated with the account, or &#39;none&#39;.
   * @return subscriptionPlan
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUBSCRIPTION_PLAN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSubscriptionPlan() {
    return subscriptionPlan;
  }


  @JsonProperty(JSON_PROPERTY_SUBSCRIPTION_PLAN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubscriptionPlan(String subscriptionPlan) {
    this.subscriptionPlan = subscriptionPlan;
  }


  public AccountStatusResponse subscriptionState(String subscriptionState) {
    this.subscriptionState = subscriptionState;
    return this;
  }

   /**
   * The current subscription state: &#39;active&#39;, &#39;pastDue&#39;, or &#39;ended&#39;.
   * @return subscriptionState
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUBSCRIPTION_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSubscriptionState() {
    return subscriptionState;
  }


  @JsonProperty(JSON_PROPERTY_SUBSCRIPTION_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubscriptionState(String subscriptionState) {
    this.subscriptionState = subscriptionState;
  }


  public AccountStatusResponse credits(Double credits) {
    this.credits = credits;
    return this;
  }

   /**
   * The number of API credits left. Can be fractional, so parse as a double-precision number.
   * @return credits
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREDITS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getCredits() {
    return credits;
  }


  @JsonProperty(JSON_PROPERTY_CREDITS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCredits(Double credits) {
    this.credits = credits;
  }


  /**
   * Return true if this AccountStatusResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountStatusResponse accountStatusResponse = (AccountStatusResponse) o;
    return Objects.equals(this.subscriptionPlan, accountStatusResponse.subscriptionPlan) &&
        Objects.equals(this.subscriptionState, accountStatusResponse.subscriptionState) &&
        Objects.equals(this.credits, accountStatusResponse.credits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subscriptionPlan, subscriptionState, credits);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountStatusResponse {\n");
    sb.append("    subscriptionPlan: ").append(toIndentedString(subscriptionPlan)).append("\n");
    sb.append("    subscriptionState: ").append(toIndentedString(subscriptionState)).append("\n");
    sb.append("    credits: ").append(toIndentedString(credits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `subscriptionPlan` to the URL query string
    if (getSubscriptionPlan() != null) {
      joiner.add(String.format("%ssubscriptionPlan%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSubscriptionPlan()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `subscriptionState` to the URL query string
    if (getSubscriptionState() != null) {
      joiner.add(String.format("%ssubscriptionState%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSubscriptionState()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `credits` to the URL query string
    if (getCredits() != null) {
      joiner.add(String.format("%scredits%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCredits()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

